### ISSUE TITLE
Comment ajouter les disciplines associées à chaque revue pour mon mémoire?

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#13]

**Comment by scameronp** [comment]
Quatre options pour les revues auxquelles plusieurs domaines sont associés : 
1-Choisir un seul domaine par revue (arbitrairement, ou en regardant moi-même manuellement, ou en demandant l'avis de l'équipe d'Érudit)
2-Associer tous les domaines à une revue & comptage unitaire (i.e. si une revue est associée à trois domaines, je compte 1 revue pour chacun de ces domaines, ce qui augmente artificiellement l'importance de cette revue par rapport aux autres et ce qui multiplie le nombre total de revues)
3-Associer tous les domaines à une revue & comptage fractionnaire (i.e. si une revue est associée à trois domaines, je compte 0,33 revue pour chacun de ces domaines, ce qui relativise l'importance de cette revue et maintient le nombre réel de revues)
4-Associer tous les domaines à une revue & fournir les deux comptages unitaire et fractionnaire

**Comment by yorrick** [comment]
Ok, techniquement en python c'est très facile, par contre il faudrait voir comment sortir ça dans un fichier csv.

Je vois 2 options:
- une colonne par domaine, avec un nombre max de domaines (ex: si sais qu'au maximum, on a 3 domaines par revue, on fait 3 colonnes)
- une seule colonne pour tout, avec les domaines séparés par des "," (ex: "domaine1,domaine2" dans une colonne)

**Comment by yorrick** [comment]
On pourrait regarder comment gérer ça en excel (les données ne sont pas à plat)
Tu peux demander à Vincent pour ça.

**Comment by scameronp** [comment]
Pour le travail exploratoire, je vais faire ça simple : 
2-Associer tous les domaines à une revue & comptage unitaire (i.e. si une revue est associée à trois domaines, je compte 1 revue pour chacun de ces domaines, ce qui augmente artificiellement l'importance de cette revue par rapport aux autres et ce qui multiplie le nombre total de revues)

J'expliquerai dans mon travail les autres possibilités et j'en reparlerai à Vincent pour la suite.

**Comment by yorrick** [comment]
On pourra faire ca en sql facilement, pour le moment par contre pour excel c'est plus simple de mettre la 1ere
