### ISSUE TITLE
Ajouter l'année et la date dans deux colonnes séparées

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#15]
On a déjà une colonne pour "time" (avec année-mois-jour heure-minute-seconde), mais j'aimerais une autre colonne pour l'année seulement, et une autre pour la date du jour (sous la forme année-mois-jour). On pourrait regarder ça ensemble, car je ne vois pas où faire la modification dans le code!

**Comment by yorrick** [comment]
Ok, est ce que tu veux ça pour le "time" ou le "local_time"?

**Comment by scameronp** [comment]
Excellente question, je n'y avais pas pensé! Je crois que c'est mieux pour le "local_time". Mais comme je ne suis pas certaine, si ce n'est pas trop compliqué, peut-on ajouter les deux?

**Comment by yorrick** [comment]
oui pas de pb!

**Comment by yorrick** [comment]
Commentaire de test

**Comment by yorrick** [comment]
test

**Comment by yorrick** [comment]
J'ai ajouté les colonnes
- date
- year
- hour

et aussi
- local_date
- local_year

**Comment by scameronp** [comment]
C'est parfait!!! Un immense merci!!! :)
