### ISSUE TITLE
Enlever les sources qui téléchargent trop

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#17]

**Comment by yorrick** [comment]
Dans un 1er temps, on pourrait juste les détecter pour essayer d'en comprendre les causes

**Comment by yorrick** [comment]
Faire la détection par user_ip, et afficher les tops qui dépassent un certain seuil

**Comment by yorrick** [comment]
Finalement, nous allons adopter une méthode basique: detecter les downloads qui dépassent un certain seuil. Avec cette méthode, on ne peut pas supprimer automatiquement les downloads, car certaines IP sont clairement des robot, alors que d'autres sont des universités (j'ai pu trouver ça en utilisant la géolocalisation des IP). Utiliser l'adresse IP du proxy ne permet pas non plus de faire la différence.
Il faudra faire le travail à la main pour ton travail de session, puis utiliser la méthode avec les ratios qui sera bcp plus efficace.
