### ISSUE TITLE
Serait-il possible de ne compter qu'une fois un usager qui télécharge plusieurs fois le même article la même journée?

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#19]
Ce n'est sans doute pas possible à cause des proxys (qui ne permettent pas de savoir s'il y a un ou plusieurs usagers derrière), mais je pose la question au cas où.

**Comment by scameronp** [comment]
Ou alors, si on comptait une fois par article / par jour / par user ip, ça nous donnerait un nombre pessimiste du nombre de téléchargements > autre option à considérer?

**Comment by yorrick** [comment]
Oui on peut le faire, à toi de voir si ça fausse les stats :)
Demande à Vincent!
