### ISSUE TITLE
Ajouter le type de device (30 min)

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#2]
Mettre trois catégories : PC, tablette ou mobile

**Comment by yorrick** [comment]
C'est faisable assez facilement ça :) Je check si j'ai un peu de temps dans la semaine

**Comment by yorrick** [comment]
Ah ça je peux le faire rapidement, dis moi si tu en as besoin :)

**Comment by scameronp** [comment]
Oui, je veux bien si c'est très rapide! :)

**Comment by yorrick** [comment]
@scameronp c'est fait, c'est dans master, on peut regarder ça ensemble avant de fermer le issue :)

**Comment by yorrick** [comment]
Supprimer la colonne device

**Comment by yorrick** [comment]
C'est bon la colonne device n'est plus ;)

**Comment by scameronp** [comment]
t = tablette
p = ordinateur portable
m = mobile
