### ISSUE TITLE
Expliquer les hypothèses pour enlever les robots

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#22]

**Comment by scameronp** [comment]
@yorrick Si je me souviens bien, tu m'as parlé de trois options :

1- L'option simple (qu'on va privilégier pour l'instant) : identifier les gros downloaders qui dépassent un certain seuil de téléchargements par jour (ex: 100 ou 200), puis regarder si le proxy_ip est le même que le user_ip. Si c'est le cas, il faut conserver ce downloader, car il s'agit du proxy d'une institution universitaire. Si ce n'est pas le cas, il s'agit sans doute d'un robot.

2- L'option compliquée (mais qui te paraît la meilleure) :  identifier les gros downloaders qui dépassent un certain seuil de téléchargements par jour (ex: 100 ou 200), puis regarder s'ils ont téléchargé des fichiers autres que l'article, comme des fichiers css. S'ils n'ont téléchargé que des articles, il s'agit de robot.
N.B. Petite question : dans le cas d'un robot qui ne télécharge que des articles, est-ce qu'un robot pourrait télécharger aussi les versions html des articles, ou seulement les PDF?

3- Une dernière option : j'ai oublié, malheureusement! Désolée!

**Comment by yorrick** [comment]
1. Cette option finalement ne permet pas de faire la suppression automatique, car l'ip du user et du proxy sont différents par ex pour l'UDM, et la même pour des IPs qui sont des robots.
2. Oui il faudrait comparer le taux de download des pdf vs (css, javascript et images). Le seuil sera déterminé à la main après expériences :)
3. Checker si les downloads sont constants dans la journée. Si c'est le cas, alors c'est surement un robot
