### ISSUE TITLE
Décrire les étapes du nettoyage des données brutes

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#23]
Voici les étapes auxquelles je pense : 
- Enlever les téléchargements de documents autres que des articles
- Enlever les erreurs (404)
- Enlever les robots connus (robot.txt)
- Enlever les robots fourbes, i.e. les gros downloaders

@yorrick  Est-ce que j'oublie quelque chose? Merci!

**Comment by yorrick** [comment]
- Enlever les téléchargements de documents autres que des articles => oui
- Enlever les erreurs (404) => ici c'est plutôt "enlever ce qui n'est pas GET avec code de retour 200"
- Enlever les robots connus (robot.txt) => ici on utilise le "user-agent". robot.txt est un fichier que tu mets sur ton site pour aider les robots
- Enlever les robots fourbes, i.e. les gros downloaders => cette partie sera faite à la main pour le moment, mais c'est l'idée oui :)
