### ISSUE TITLE
Quelle est la différence entre Interesting, Extracted et Downloads dans le script?

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#24]
@yorrick

**Comment by yorrick** [comment]
Interesting = la ligne contient "GET", "200", "ar.pdf" ou "ar.html", c'est un pré-filtre.
Extracted = Après le pré-filtre, j'ai été capable d'extraire toutes les infos (normalement ça fonctionne tout le temps, car le pré filtre supprime presque toutes les lignes étranges, mais il peut quand même rester  des lignes mal formatées qu'on ne peut pas extraire)
Downloads => Nombre de downloads, par des humains (les robots sont supprimés, du mieux qu'on peut)

**Comment by scameronp** [comment]
On en a rediscuté, et c'est plutôt : 

Interesting = la ligne contient "GET", "/revue", "200", ".pdf" ou ".html", c'est un pré-filtre.
Extracted = Après le pré-filtre, n'extraire que "ar.html" et "ar.pdf" dans la colonne correspondant à l'URL de l'article.
Downloads => Nombre de downloads, par des humains (les robots gentils sont supprimés, du mieux qu'on peut)
