### ISSUE TITLE
Quel est le meilleur moyen d'enlever les méchants robots?

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#25]
@yorrick  J'ai repéré les méchants robots en regardant à la main les adresses ip des tops downloaders (seuil = user_ip qui téléchargent plus de 300 articles / jour). La liste se trouve dans le fichier Excel que je t'ai envoyé sur HipChat (feuille 4). Comment devrait-on les enlever à ton avis? Ça me paraît un peu long de les enlever à la main dans Excel, mais ça se fait aussi. Dis-moi!

**Comment by yorrick** [comment]
Je peux améliorer mon script pour qu'il lise un fichier en entrée, et supprime les IP backlistées. Il faut juste que tu me mette la liste des IPs dans un commentaire ici :)

**Comment by scameronp** [comment]
Ok merci!!!! Les voilà : 

41.83.44.215
52.16.55.221
88.190.11.232
217.69.133.28
41.140.235.43
93.158.150.21
82.233.222.35
119.188.12.12
176.121.11.18
79.86.224.121
41.83.47.224
46.229.160.208
185.12.14.122
46.229.160.208
46.229.160.208
46.229.160.208
85.31.219.79
46.229.160.208
41.250.30.253
96.21.252.22
41.97.203.184
41.188.62.3
174.93.173.196
41.224.151.79
46.229.160.208
209.190.38.162
85.31.219.92
94.23.1.19
144.76.163.48
144.76.155.8
148.251.69.136
79.86.224.121
46.229.160.208
148.251.75.46
88.198.56.239
148.251.124.42
41.250.84.28
144.76.185.173
88.198.56.239
144.76.185.173
144.76.155.8
148.251.75.46
144.76.201.69
148.251.69.136
85.31.219.72
144.76.163.48
142.91.199.178
93.186.202.244
173.208.148.43
93.186.202.253
46.229.160.208
147.255.205.194
85.31.219.62
85.31.219.66
85.31.219.23
85.31.219.94
85.31.219.67
41.230.244.39
173.208.148.43
85.31.219.63
85.31.219.56
93.186.202.239
173.208.148.51
85.31.219.91
154.65.34.204
173.208.148.51
46.229.160.208
93.186.202.241
188.138.89.96
173.208.148.51
195.24.209.20
144.76.185.173
85.31.219.60
144.76.185.173
144.76.201.69
144.76.163.48
144.76.201.69
88.198.56.239
93.186.202.198
148.251.124.42
148.251.124.42
93.186.202.197
148.251.69.136
88.198.56.239
148.251.75.46
148.251.69.136
144.76.155.8
46.229.160.208
192.95.19.209
148.251.75.46
148.251.69.136
136.243.24.42
