### ISSUE TITLE
Gérer les changements de noms des revues

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#26]
Lorsqu'une revue change de nom, l'abréviation qui est utilisée dans l'URL change. Érudit m'a donné la liste des revues qui ont changé de nom (voir le document Erudit_Global_Global_EndPublication_2015-11-23.txt  que j'ai joint dans HipChat). Il faudrait trouver un moyen d'associer l'ancien nom au nouveau nom dans la base de données SQL.

**Comment by yorrick** [comment]
Ok, je vais ajouter une colonne dans le csv, qui va contenir l'id unique que tu as choisi pour la revue

**Comment by yorrick** [comment]
Pas besoin du nom complet de la revue
