### ISSUE TITLE
Identifier les revues en libre accès complet

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#27]
Environ 20 revues sont en libre accès complet (aucun embargo) sur Érudit (voir le document Erudit_Global_Global_Openaccess_2015-11-23.txt que j'ai joint dans HipChat). Il faudrait trouver un moyen d'identifier les revues OA dans la base de données SQL pour ne pas que j'en tienne compte lorsque j'observerai l'effet de la fin de l'embargo sur le nombre de téléchargements i.e. la courbe d'obsolescence avant et après la fin de l'embargo.

**Comment by scameronp** [comment]
Je réfléchis, mais serait-il possible d'ajouter cette information dans le script pour mon travail de session? Je pourrais regarder, avec mon échantillon, s'il y a une différence entre le nombre moyen de téléchargements des articles dans des revues en libre accès complet et entre le nombre moyen des autres articles.

**Comment by yorrick** [comment]
Oui c'est possible je peux ajouter une colonne dans le fichier résultat en csv
