### ISSUE TITLE
Ajouter la 1re discipline de chaque revue

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#29]

**Comment by scameronp** [comment]
J'ai un fichier Excel avec tous les domaines des revues. J'avais tout d'abord pensé faire l'option 2 pour mon travail de session : "Associer tous les domaines à une revue & comptage unitaire". Pour ce faire, j'avais dupliqué les revues lorsqu'elles avaient plus qu'une discipline associée, de manière à avoir seulement deux colonnes: les revues et les disciplines. 
Cependant, je me rends compte que ça ne règle pas notre problème... Comment sortir les données de téléchargements avec une seule discipline par revue par téléchargement si j'ai dupliqué les revues?? Ça ne marche pas.

Je vais donc choisir l'option simple et radicale pour mon travail de session : ne conserver que la première discipline de chaque revue. Serait-il possible d'ajouter cela au script?

**Comment by scameronp** [comment]
Envoyer à Yorrick un fichier csv avec: 
abréviation de la revue1 virgule discipline1
sur des lignes différentes

**Comment by yorrick** [comment]
Finalement nous allons faire ca avec le fichier json des revues
