### ISSUE TITLE
Ajouter une notion de date dans le full_oa du fichier JSON

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#30]
Par exemple : une revue qui a changé de nom, et après avoir changé de nom, elle a cessé d'être publiée en 2003. Elle n'était pas full open access initialement, mais la période d'embargo étant terminée, tous les numéros sont ajd en open access. J'ai indiqué "false" dans full_oa pour l'instant, vu qu'elle n'était pas initialement oa.

Cet exemple nous fait penser qu'il faudrait peut-être ajouter une date dans le champ full oa : ça permettrait de calculer la date de fin de l'embargo des revues. On pourrait écrire pour les revues qui ne sont pas en full oa : 
année en cours - 2 ans = année de début de l'oa

**Comment by yorrick** [comment]
Comme nous avons vu ensemble, il n'y a finalement pas de revue qui a changé de status, donc nous n'avons pas besoin d'ajouter de date au champ full_oa.
Aussi, on peut déjà calculer aujourd'hui même sans le référentiel, si un download concerne un article sous embargo ou non (sous embargo = (année du download - année de publication) < 2 ans)
