### ISSUE TITLE
Préciser la date de fin de l'embargo de chaque revue

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#35]
- Selon Émilie, tous les numéros d'une année tombent en OA en même temps, DONC par exemple : en janvier 2016, tous les numéros de l'année 2014 de la revue X vont tomber en OA (y compris le numéro de décembre 2014)
- Aller voir sur le site de la plateforme, pour chaque revue (qui n'est pas full_oa), quels sont les numéros qui sont passés en OA pour chaque année (de 2010 à 2015)
- Ajouter dans le fichier JSON la liste des volumes et numéros qui passent en OA pour chaque année (de 2010 à 2015) ; @yorrick Quelle serait la meilleure façon de noter cette information?
- Ajouter dans le script le calcul de la date de fin de l'embargo RELATIVEMENT à la date du téléchargement

**Comment by yorrick** [comment]
Attends avant d'ajouter des infos dans le json, c'est peut être pas nécessaire :)

**Comment by scameronp** [comment]
Ok, on s'en reparle!

**Comment by yorrick** [comment]
En fait, le fait que tous les numéros d'une année tombent en OA en même temps nous arrange, car on faisait déjà cette approximation quand on calculait le champ "embargo".

Même sans avoir la liste des numéros et des volumes, on peut savoir si l'article est sous embargo juste avec l'année de publication, c'est pour ça que je te disais qu'il n'y avait pas besoin de rajouter des infos dans le json.

**Comment by yorrick** [comment]
Pour le calcul de la date de fin de l'embargo, il suffit juste de regarder si la différence entre la date de téléchargement et la date de publication est supérieure à 2ans (ça c'est déjà fait), si la revue est pas full OA (ça je peux l'ajouter).

**Comment by scameronp** [comment]
En effet, tu as sûrement raison!! Le seul truc que je me demande, c'est si notre calcul de "la différence entre les deux dates doit être supérieure à deux ans" est bon, car étant donné ce qu'Émilie m'a dit, la durée de l'embargo est parfois MOINS que 2 ans. Par exemple, un article publié en décembre 2014 devient OA en janvier 2016, ce qui fait à peine plus d'un an...

**Comment by scameronp** [comment]
Mais d'un autre côté, si on arrondit à l'année, notre calcul est bon, car 2016-2014 = 2 ...

**Comment by yorrick** [comment]
C'est bon je viens d'ajouter le support de full_oa pour le calcul du champ "embargo": si la revue est full_oa, embargo est toujours false, peut importe les dates

**Comment by yorrick** [comment]
Mmmmh non le calcul est pas bon parce que pour le moment je dis que embargo = oui si age <= 2
