### ISSUE TITLE
Ajouter le nom complet des revues

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#4]

**Comment by scameronp** [comment]
@yorrick Attends avant de le faire, car je suis en train d'ajouter les disciplines dans mon document Excel. C'est peut-être mieux de tout faire en même temps?

**Comment by scameronp** [comment]
On va attendre pour cette question parce que je ne suis pas certaine que c'est utile finalement. Je pense que c'est peut-être mieux de garder l'abréviation de la revue seulement dans les fichiers (les noms complets sont parfois assez longs). Après avoir filtré et déterminé le top 10 des revues pour un domaine, par exemple, là je pourrai mentionner leur nom complet dans le texte (mais pas dans les graphiques).

**Comment by yorrick** [comment]
On laisse faire :)
