### ISSUE TITLE
Version HTML des articles : enlever numéros de revue qui ne sont pas en traitement complet (3 hrs)

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#46]
Nous avons remarqué que certains liens d'articles téléchargés ne pointent pas vers le plein texte. 
J'ai qualifié un échantillon à la main + parlé à Vincent:
- Il faut retirer tous les téléchargements qui se terminent par '%.html%' (par exemple: '%.html?vue=resume' ; '%.html?vue=plan' ; '%.html?vue=biblio' ; etc.) SAUF ceux qui se terminent par '.html?vue=integral'.
- Pour les téléchargements qui se terminent simplement par '%.html', j'ai demandé de me fournir la liste des revues qui ont à la fois une version PDF et HTML, et depuis quelle année elles ont une version HTML. 
- Il faut retirer tous les téléchargements qui se terminent par '%.html%' pour les revues qui n'ont qu'une version PDF seulement.

**Comment by scameronp** [comment]
Premier point terminé. En attente d'une réponse pour les autres points (début février)

**Comment by scameronp** [comment]
C'est bon, j'ai les informations sur les formats de revue! On est prêt à faire cette partie!

**Comment by scameronp** [comment]
Traitement minimal = PDF uniquement
Traitement complet = PDF + HTML (il y a toujours un PDF envoyé par les éditeurs de la revue)

Normalement, les articles d'un numéro sont tous sensés avoir le même format, mais quelques exceptions (ex: 4 articles en traitement minimal et 11 en traitement complet dans un même numéro).
Solution que je propose : évaluer combien il y a d'exception à peu près, et s'il n'y en a pas beaucoup : arrondir au numéro (ex: 4 articles en traitement minimal et 11 en traitement complet = considérer ce numéro comme en traitement complet).

Problème pour certaines revues (du fond UNB) qui ont une date de production dans les années 1970-1980.
Solution que je propose : utiliser la date du premier téléchargement d'un article dans un numéro donné comme date de production de tous les articles de ce numéro, pour les numéros où la date de production est antérieure à la création de la plateforme (1998) dans le rapport envoyé.

**Comment by yorrick** [comment]
C'est en cours!

**Comment by yorrick** [comment]
C'est bon!

**Comment by yorrick** [comment]
En fait je vais réouvrir ça pour qu'on fasse les vérifications ensemble :)

**Comment by yorrick** [comment]
Pour vérifier dans les données tu peux faire

select DISTINCT publication_year
from download d
  INNER JOIN article a on a.id = d.article_id
  INNER JOIN issue i on i.id = a.issue_id
  INNER JOIN volume v on v.id = i.volume_id
  INNER JOIN journal j on j.id = v.journal_id
where journal = 'crimino' and url like '%html'
order by publication_year;

par exemple pour crimino

"full_text_html": [
      {"start_year": 2003}
    ],

et comparer le résultat avec 

select DISTINCT publication_year
from download d
  INNER JOIN article a on a.id = d.article_id
  INNER JOIN issue i on i.id = a.issue_id
  INNER JOIN volume v on v.id = i.volume_id
  INNER JOIN journal j on j.id = v.journal_id
where journal = 'crimino' 
order by publication_year;
