### ISSUE TITLE
McGill

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#49]
@yorrick En bonus, on pourrait ajouter:
- les référents

@sarah 
- Commencer par voir les disciplines et finir d'écrire mon texte ;
- Je pourrais ensuite refaire l'ensemble des graphiques avec la version actuelle des données qui ne contient QUE les '.html?vue=integral' et non pas les '.html' tout court (on attend au début février le rapport avec les dates de changement de format des revues avant d'ajouter les '.html' de certaines revues).

**Comment by yorrick** [comment]
Les référents sont là, dans la version v0.2 :)
