### ISSUE TITLE
Finir disciplines (1 hr)

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#50]

**Comment by yorrick** [comment]
Un exemple de requête pour aller faire un count des downloads par discipline 

select count(_), domain
from download dw, journal j, domain d
where dw.journal_id = j.id and j.journal = d.journal
group by domain
order by count(_) desc;

**Comment by scameronp** [comment]
Équivalent à:

select count(*) as number, domain
    from download dw, domain dm
    where dw.journal = dm.journal
    group by domain
    order by number desc;

Parce que le nom de la revue est utilisé comme foreign key dans la table domain (c'est pourquoi je peux passer directement de la table download à la table domain, sans passer par la table journal).
