### ISSUE TITLE
Optimisation de la base de données (3 hrs)

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#51]
J'ai mis sur Hipchat un document avec l'ensemble de mes requêtes SQL. Voici quand même des exemples de requêtes qui sont plus longues à exécuter sur mon ordi:

select user_ip, proxy_ip, date(time) as date, count(*) as number 
    from download
    group by user_ip, date, proxy_ip
    order by number desc;
(terminée en 90 364 ms)

select distinct publication_year, url from download
    where url not like '%pdf%'
        and url like '%html'
    group by publication_year, url
    order by publication_year desc;
(terminée en 19 271 ms)

select download_hour, country, count(_) as number
    from download
    where download_hour is not null
        and country in 
            (select country from download 
                group by country 
                order by count(_) desc 
                limit 5)  
    group by download_hour, country
    order by download_hour asc;
(terminée en 22 290 ms)

select download_hour, country, count(_) as number, is_robot, is_bad_robot, user_ip
    from download
    where download_hour is not null
        and country in 
            (select country from download 
                group by country 
                order by count(_) desc 
                limit 5) 
    group by download_hour, country, is_robot, is_bad_robot, user_ip
    order by download_hour asc, is_robot, is_bad_robot;
(terminée en 66 621 ms)

**Comment by yorrick** [comment]
C'est bon c'est fait, par contre il va falloir que tu changes un peu tes requêtes.
Le bon côté des choses, c'est que 
- les requêtes ont l'air plus rapide (j'ai testé avec tes 4 requêtes lentes, qui ont l'air d'aller 20% plus vite)
- la construction de la DB est je pense (j'ai pas mesuré avec précision) 2 fois plus rapide
- la DB prend 7 fois moins de place sur le disque dur 

Je garde les changements sous le coude, dis moi quand tu es prête pour que je les ajoute à la version principale (on pourra revoir tes requêtes rapidement)
