### ISSUE TITLE
Erreur dans le parsing: Malformed IP address

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#60]
(download-data) download-data git:(bdc9c7c) ✗ ./extract/parse_downloads.py data/_.log && cat data/_.log.csv > data/all.log.csv
Parsing file data/100415.log
Parsing file data/100927.log
Parsing file data/110122.log
Parsing file data/110516.log
data/110122.log: Total: 292890 => parsable: 50439 (17.22%) => download: 48833 (16.67%) => considered_human: 13837 (4.72%)
Parsing file data/110304.log
data/110516.log: Total: 348956 => parsable: 47712 (13.67%) => download: 42443 (12.16%) => considered_human: 18029 (5.17%)
Parsing file data/110727.log
data/100415.log: Total: 310689 => parsable: 52469 (16.89%) => download: 49683 (15.99%) => considered_human: 22654 (7.29%)
Parsing file data/100519.log
data/100927.log: Total: 456784 => parsable: 61664 (13.50%) => download: 55369 (12.12%) => considered_human: 26351 (5.77%)
Parsing file data/101005.log
data/110727.log: Total: 295516 => parsable: 40324 (13.65%) => download: 38186 (12.92%) => considered_human: 11178 (3.78%)
Parsing file data/110813.log
data/110304.log: Total: 438581 => parsable: 51435 (11.73%) => download: 49676 (11.33%) => considered_human: 17052 (3.89%)
Parsing file data/110314.log
data/100519.log: Total: 286763 => parsable: 45416 (15.84%) => download: 42483 (14.81%) => considered_human: 19835 (6.92%)
Parsing file data/100604.log
data/110813.log: Total: 191987 => parsable: 30766 (16.03%) => download: 29676 (15.46%) => considered_human: 6345 (3.30%)
Parsing file data/110825.log
data/100604.log: Total: 236552 => parsable: 41849 (17.69%) => download: 38735 (16.37%) => considered_human: 12802 (5.41%)
Parsing file data/100630.log
data/101005.log: Total: 550287 => parsable: 53837 (9.78%) => download: 51303 (9.32%) => considered_human: 24453 (4.44%)
Parsing file data/101202.log
data/110825.log: Total: 338382 => parsable: 42728 (12.63%) => download: 40039 (11.83%) => considered_human: 11398 (3.37%)
Parsing file data/110831.log
data/110314.log: Total: 528634 => parsable: 56499 (10.69%) => download: 51330 (9.71%) => considered_human: 22577 (4.27%)
Parsing file data/110315.log
data/100630.log: Total: 337817 => parsable: 38229 (11.32%) => download: 36281 (10.74%) => considered_human: 11064 (3.28%)
Parsing file data/100917.log
data/101202.log: Total: 408776 => parsable: 60273 (14.74%) => download: 58178 (14.23%) => considered_human: 22163 (5.42%)
Parsing file data/101206.log
data/110831.log: Total: 563344 => parsable: 69893 (12.41%) => download: 65993 (11.71%) => considered_human: 12496 (2.22%)
Parsing file data/111120.log
data/100917.log: Total: 323985 => parsable: 44820 (13.83%) => download: 42591 (13.15%) => considered_human: 16159 (4.99%)
Parsing file data/120304.log
data/110315.log: Total: 493436 => parsable: 46082 (9.34%) => download: 43671 (8.85%) => considered_human: 22448 (4.55%)
Parsing file data/110407.log
data/111120.log: Total: 424152 => parsable: 64698 (15.25%) => download: 63494 (14.97%) => considered_human: 25389 (5.99%)
Parsing file data/111125.log
data/101206.log: Total: 497080 => parsable: 71207 (14.33%) => download: 64829 (13.04%) => considered_human: 24474 (4.92%)
Parsing file data/101212.log
data/120304.log: Total: 429478 => parsable: 66593 (15.51%) => download: 63640 (14.82%) => considered_human: 21081 (4.91%)
Parsing file data/120314.log
data/110407.log: Total: 446605 => parsable: 50506 (11.31%) => download: 48746 (10.91%) => considered_human: 20166 (4.52%)
Parsing file data/120812.log
data/120812.log: Total: 272504 => parsable: 46754 (17.16%) => download: 40683 (14.93%) => considered_human: 10134 (3.72%)
Parsing file data/120824.log
data/101212.log: Total: 417816 => parsable: 58849 (14.08%) => download: 56567 (13.54%) => considered_human: 20824 (4.98%)
Parsing file data/121206.log
data/111125.log: Total: 495386 => parsable: 47244 (9.54%) => download: 46285 (9.34%) => considered_human: 22516 (4.55%)
Parsing file data/111206.log
data/120314.log: Total: 662397 => parsable: 61452 (9.28%) => download: 59483 (8.98%) => considered_human: 26026 (3.93%)
Parsing file data/120407.log
data/120824.log: Total: 422408 => parsable: 58885 (13.94%) => download: 57087 (13.51%) => considered_human: 13377 (3.17%)
Parsing file data/120901.log
data/111206.log: Total: 458607 => parsable: 46775 (10.20%) => download: 45404 (9.90%) => considered_human: 28702 (6.26%)
Parsing file data/111230.log
Parsing file data/130314.log
Traceback (most recent call last):
  File "./extract/parse_downloads.py", line 96, in <module>
    pool.map(process_file, build_process_file_param_list(params, journals))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: Malformed IP address

**Comment by yorrick** [comment]
data/121206.log est fautif
