### ISSUE TITLE
Supprimer la table "disciplines" et mettre la nouvelle discipline de chaque revue dans la table "revues"

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#64]

**Comment by scameronp** [comment]
Voir comment modifier le référentiel de revues JSON
Tout mettre ou non? 
Grande discipline ENG-FRA, Discipline ENG-FRA, Spécialité ENG-FRA

**Comment by yorrick** [comment]
Je pensais ajouter les colonnes suivantes dans la table journal

general_discipline, discipline, speciality, general_discipline_fr, discipline_fr, speciality_fr

Et aussi supprimer la table "domain"
