### ISSUE TITLE
Vérifier si la librairie de géolocalisation permet de voir la ville des téléchargements

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#72]

**Comment by yorrick** [comment]
Je pense que ça se fait :)

Il faut télécharger la base de donnée gratuite qui contient les villes sur le site de MaxMind: http://dev.maxmind.com/geoip/geoip2/geolite2/#Databases

Ensuite, il faut ouvrir la DB manuellement dans le code avec 

with open_database("/Users/yorrick/Downloads/GeoLite2-City.mmdb") as db:
    result = db.lookup("198.58.153.76")

Puis aller chercher la ville avec 

result.get_info_dict().get('city').get('names').get('en')

**Comment by yorrick** [comment]
@scameronp il y a des villes dans environ 70% des downloads
