### ISSUE TITLE
Problèmes avec les fichiers CSV et Excel

### ISSUE THREAD

**Issue by scameronp** [yorrick/download-data#9]
J'ai les mêmes problèmes à la fois avec la version CSV et la version Excel du fichier 110302.log : 
1) J'ai ajouté une ligne avec les en-têtes des colonnes à la main, mais je n'arrive pas à figer les volets sous l'en-tête. Ça fige les volets automatiquement sous la ligne 21, sans que je puisse le changer.
2) Lorsque j'essaie de trier les données, il y a toujours la première ligne de téléchargement (qui est maintenant la 2e ligne, puisque j'ai ajouté une ligne d'en-tête) qui ne veut pas être triée.

**Comment by yorrick** [comment]
@scameronp est ce que tu as ouvert le fichier 110302.log ou 110302.log.csv ?
